import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          {/* TODO: Add header */}
          <div className="bg-slate-400 p-3">Header</div>
          <main className="flex flex-1">{children}</main>
          <div className="bg-slate-400 p-2">Footer</div>
          {/* TODO: Add footer */}
        </div>
      </body>
    </html>
  );
}
